// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioBackend.Infrastructure.Data;

#nullable disable

namespace PortfolioBackend.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260223054428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "N5 Now",
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Period = "20 Feb 2025 - Actualidad",
                            Project = "Sistema de Gestión de Formularios",
                            Role = "Desarrolladora de Software",
                            StartDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "[\"React\",\"TypeScript\",\"C# .NET\",\"MongoDB\",\"PostgreSQL\",\"Elsa Workflows\",\"SQL\"]",
                            Usage = "Desarrollo de interfaces y tablas CRUD + creación de controladores, repositorios y migraciones SQL para base de datos + pruebas unitarias e integración"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Aeroméxico",
                            CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Period = "20 Feb 2025 - Actualidad",
                            Project = "Sistema de Pagos Móviles Aeroméxico",
                            Role = "Tester",
                            StartDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "[\"Java 17\",\"Spring Boot\",\"MongoDB\",\"Sabre GDS\",\"AWS SQS\",\"WebSocket\",\"Postman\"]",
                            Usage = "Pruebas funcionales e integración de sistema de pagos móviles + validación de flujos de pago, emisión de tickets y reembolsos + verificación de endpoints REST y notificaciones WebSocket"
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HoursInvested")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sistema web Full Stack para gestión de recursos comunitarios",
                            GithubUrl = "https://github.com/usuario/micomunidad",
                            HoursInvested = 150,
                            ImageUrl = "/images/proyecto-gestion-recursos.png",
                            Semester = 7,
                            Title = "MiComunidad - Gestión de Recursos",
                            Type = "Web"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dashboard de Business Intelligence con visualizaciones interactivas",
                            GithubUrl = "https://github.com/usuario/dashboard-bi",
                            HoursInvested = 100,
                            ImageUrl = "/images/dashboard-bi.png",
                            Semester = 7,
                            Title = "Dashboard BI",
                            Type = "Web"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sistema de pagos móviles para aerolínea",
                            GithubUrl = "https://github.com/usuario/pagos-aeromexico",
                            HoursInvested = 160,
                            ImageUrl = "/images/pagos-aeromexico.png",
                            Semester = 8,
                            Title = "Pagos Móviles Aeroméxico",
                            Type = "Web"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "API REST para plataforma de comercio electrónico",
                            GithubUrl = "https://github.com/usuario/api-ecommerce",
                            HoursInvested = 90,
                            ImageUrl = "/images/api-ecommerce.png",
                            Semester = 5,
                            Title = "API E-commerce",
                            Type = "API"
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.ProjectTechnology", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("ProjectTechnologies");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            TechnologyId = 5
                        },
                        new
                        {
                            ProjectId = 1,
                            TechnologyId = 6
                        },
                        new
                        {
                            ProjectId = 1,
                            TechnologyId = 18
                        },
                        new
                        {
                            ProjectId = 1,
                            TechnologyId = 15
                        },
                        new
                        {
                            ProjectId = 2,
                            TechnologyId = 11
                        },
                        new
                        {
                            ProjectId = 2,
                            TechnologyId = 13
                        },
                        new
                        {
                            ProjectId = 3,
                            TechnologyId = 3
                        },
                        new
                        {
                            ProjectId = 3,
                            TechnologyId = 10
                        },
                        new
                        {
                            ProjectId = 3,
                            TechnologyId = 13
                        },
                        new
                        {
                            ProjectId = 4,
                            TechnologyId = 18
                        },
                        new
                        {
                            ProjectId = 4,
                            TechnologyId = 15
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("YearsOfExperience")
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "C",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Name = "C++",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Name = "Java",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Name = "POO",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Name = "Angular 21",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Name = "TypeScript 5.9",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frontend",
                            Name = "JavaScript",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Frontend",
                            Name = "HTML",
                            YearsOfExperience = 3m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Frontend",
                            Name = "CSS",
                            YearsOfExperience = 3m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Backend",
                            Name = "Spring Boot",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Frontend",
                            Name = "React",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Backend",
                            Name = "Node.js",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Database",
                            Name = "MongoDB",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Database",
                            Name = "PostgreSQL",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Database",
                            Name = "SQL Server",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Tools",
                            Name = "Git",
                            YearsOfExperience = 2m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Tools",
                            Name = "Docker",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Backend",
                            Name = "ASP.NET Core",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Backend",
                            Name = "Elsa Workflows",
                            YearsOfExperience = 0.5m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Tools",
                            Name = "New Relic",
                            YearsOfExperience = 0.5m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Mobile",
                            Name = "Android",
                            YearsOfExperience = 1m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Tools",
                            Name = "Postman",
                            YearsOfExperience = 2m
                        });
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.ProjectTechnology", b =>
                {
                    b.HasOne("PortfolioBackend.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortfolioBackend.Domain.Entities.Technology", "Technology")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectTechnologies");
                });

            modelBuilder.Entity("PortfolioBackend.Domain.Entities.Technology", b =>
                {
                    b.Navigation("ProjectTechnologies");
                });
#pragma warning restore 612, 618
        }
    }
}
